name: CI Check

on:
  push:
    branches: ["main"]

jobs:
  typecheck:
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - run : npm run lint
      - run : npx tsc --noEmit

